### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by chrismarquardt** [CMahaff/lasim#10]
**Describe the Bug**
Got a 400 Bad Request error when trying to use lasim to download from feddit.de 

**Information**
LASIM Version: 0.1.1
LASIM Profile Version: ?
Lemmy Source Instance URL: feddit.de
Lemmy Source Instance Version: ?
Lemmy Target Instance URL: n/a
Lemmy Target Instance Version: n/a

**Output of LASIM**
```
Logging in as xxxx@xxxxxx.xxx
ERROR: Failed Login - HTTP status client error (400 Bad Request) for url (https://feddit.de/api/v3/user/login)
```

**Comment by CMahaff** [comment]
Thanks for the report. I've made a registration application to feddit.de. Once I have an account, I'll see if I run into the same thing.

I assume you ran into this multiple times? Sometimes the popular instances might throw Bad Request errors when they are overloaded.

**Comment by CMahaff** [comment]
I created an account on feddit.de and was able to download and upload without issue.

Closing this on the assumption that it was temporary server load.

**Comment by neosheo** [comment]
I'm having this issue when attempting to upload to https://discuss.tchncs.de. I made an account and can log in on the webbrowser but get 400 error on lasim
