### ISSUE TITLE
Validate login target is a Lemmy instance  before sending credentials

### ISSUE THREAD

**Issue by CMahaff** [CMahaff/lasim#14]
**Describe the Bug**
This tip was posted here: https://lemmy.world/post/1441882
While this is hardly fool-proof, it's probably wise to do at least this basic check before we send a users credentials out over the internet in case they fat-fingered it.

**Information**
LASIM Version: 0.1.2
LASIM Profile Version: 1
Lemmy Source Instance URL: N/A
Lemmy Source Instance Version: N/A
Lemmy Target Instance URL: N/A
Lemmy Target Instance Version: N/A

**Output of LASIM**
N/A

**Comment by aidandenlinger** [comment]
I'm interested in implementing the basic `getSite` check, will look into it today!
