### ISSUE TITLE
More security vendors are now tagging lasim as (password stealing) Trojan

### ISSUE THREAD

**Issue by Tipoff4317** [CMahaff/lasim#15]
OS: Windows 11 Pro
File: Lasim.exe
Lasim version: [v0.1.2](https://github.com/CMahaff/lasim/releases/tag/v0.1.2) 
VirusTotal analysis: https://www.virustotal.com/gui/file/9cbddd9276b5ff0fb3bcf982f766f533053c6852162b314a6536faab6bce0da5/detection

Lasim version: [v0.1.1](https://github.com/CMahaff/lasim/releases/tag/v0.1.1) 
VirusTotal analysis: https://www.virustotal.com/gui/file/3da7727225c201328391fa44eca060f6e060978dbbd7b0a163d5a083e5d81bc5/detection

FYI.  Not sure if you can do anything with it.  Not sure if it is an issue.

**Comment by CMahaff** [comment]
Yeah that's really odd. I don't know what would be tripping it up about 0.1.2, other than that it's newer.

I can definitely find references to false positives on virustotal:
- https://www.reddit.com/r/rust/comments/qa7tqk/rust_executable_flagged_as_malware_by_virustotal/
- https://www.reddit.com/r/golang/comments/k5ac91/tcp_chat_application_being_detected_as_virus/

So in short, 3/70 deciding it's a virus is not unheard of. Especially for a program that actively prompts users for credentials I guess.

I always use the versions compiled by GitHub, so even if my personal machine was infected somehow, what gets uploaded should be safe.

Obviously for anyone concerned, you can always examine the code and then build it from source:
- https://www.rust-lang.org/tools/install
- https://doc.rust-lang.org/cargo/commands/cargo-build.html

Or download the results from Github itself: https://github.com/CMahaff/lasim/actions
(i.e. the latest 0.1.2 is here: https://github.com/CMahaff/lasim/actions/runs/5549283894)

As for fixing this, not sure what else to do except look into signing the windows version, which from the above threads, might make them shut up.

**Comment by CMahaff** [comment]
Hah, just hit "re-analyze" on the same file and a completely different set of matches are now shown, 4/70.

(sorry, I think it removed your original scan results - I thought it would generate new ones).

I'm prepared to close this since the results seem kind of random, unless there is an action you'd like me to take.

**Comment by Tipoff4317** [comment]
OK.  I can't think of any suggestions anyway.  Thx for responding.
