### ISSUE TITLE
Issue During Download - 'infinite_scroll_enabled'

### ISSUE THREAD

**Issue by seanpr** [CMahaff/lasim#27]
**Describe the Bug**
I'm trying to download my settings and subscribed communities from instance to import in another instance. I'm guessing it might be a Lemmy instance version problem (0.18.2 vs 0.18.3), but wanted to double check. Error happens after logging in and the Download process starts.

**Information**
LASIM Version: 0.2.1
LASIM Profile Version:
Lemmy Source Instance URL: https://lemmy.blahaj.zone
Lemmy Source Instance Version: 0.18.2-rc.2-50-g08455003c-kt.2
Lemmy Target Instance URL: <didn't get to this>
Lemmy Target Instance Version: <didn't get to this>

**Output of LASIM**
Logging in as <username>
Login Successful.
ERROR: Failed to fetch Profile - error decoding response body: missing field `infinite_scroll_enabled` at line 1 column 6419

**Comment by seanpr** [comment]
Looks like I was write, sorry for the quick post. But should I use the old version of LASIM to download, then new version to Upload - the new instance is 0.18.3)? Or will the old version work when uploading to a newer instance version?

**Comment by CMahaff** [comment]
You closed this so I assume you got it already, but yes, you'd use the old version of LASIM to download it, then use the new version of LASIM to upload it.

**Comment by seanpr** [comment]
Yup, I got it working. Although, the old version worked for the newer 0.18.3 instance as well. Next time... I know what to do. Thank you for creating this tool!
