### ISSUE TITLE
Mobile release

### ISSUE THREAD

**Issue by trymeouteh** [CMahaff/lasim#31]
Please make an app for Android and iOS

**Comment by CMahaff** [comment]
Unfortunately the technologies chosen for this project are not compatible with mobile, so a mobile release would require a full re-write.

If I could go back in time I might have chosen differently, but I think for now this will be desktop only.

You might want to take a look at some of the Lemmy apps - I swear one of them claimed it could transfer subscriptions.

**Comment by aidandenlinger** [comment]
It looks like someone is working on a project like this that'll come out in the near future, [post about it from !android@lemmy.world here](https://sh.itjust.works/post/2612183).
