### ISSUE TITLE
V0.2.2 not opening on mac

### ISSUE THREAD

**Issue by evanpaul14** [CMahaff/lasim#38]
**Describe the Bug**
v0.2.2 does not open on mac. v0.2.1 does work
**Information**
LASIM Version: v0.2.2
LASIM Profile Version: I could not view
Lemmy Source Instance URL: n/a
Lemmy Source Instance Version: n/a
Lemmy Target Instance URL: n/a
Lemmy Target Instance Version: n/a

**Output of LASIM**
/Users/username/Downloads/GNUSparseFile.0/lasim ; exit;                         
username@my-Mac-mini-2 ~ % /Users/username/Downloads/GNUSparseFile.0/lasim ; exit;
zsh: exec format error: /Users/username/Downloads/GNUSparseFile.0/lasim

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by CMahaff** [comment]
Thank you for reporting this.

Looks like the archive I downloaded from Github got corrupted somehow.

I've published a fixed artifact (from what I can tell anyway) to the 0.2.2 release.

Let me know if you see any further issues.
