### ISSUE TITLE
Error with Upload to lemmy.ml

### ISSUE THREAD

**Issue by esmoyer** [CMahaff/lasim#4]
**Describe the Bug**
Logging this officially from https://lemmy.world/comment/965788

Download profile from lemmy.world (works great) but go to upload to lemmy.ml and get 

```
Logging in as smoysauce
ERROR: Failed Login - HTTP status client error (403 Forbidden) for url (https://lemmy.ml/api/v3/user/login)
```
MFA is disabled for lemmy.ml. Tried using username as well as email. Password is copied and pasted from password manager which works when auto-filling to login to actual lemmy.ml site.

Let me know if you need anything else from me, or need to me test anything, thanks!

**Information**
LASIM Version: 0.1.0
LASIM Profile Version: v1 (? sorry not sure where this is)
Lemmy Source Instance URL: lemmy.world
Lemmy Source Instance Version: BE: 0.18.1
Lemmy Target Instance URL: lemmy.ml
Lemmy Target Instance Version: BE: 0.18.1

**Output of LASIM**
IMPORTANT: Make sure you do not post your authentication tokens here by accident!

```
Logging in as smoysauce
ERROR: Failed Login - HTTP status client error (403 Forbidden) for url (https://lemmy.ml/api/v3/user/login)
```

**Comment by CMahaff** [comment]
Sorry you are having trouble! I just made an account on lemmy.ml - waiting for them to accept, and then I'll see if I run into the same issues.

**Comment by esmoyer** [comment]
> Sorry you are having trouble! I just made an account on lemmy.ml - waiting for them to accept, and then I'll see if I run into the same issues.

No need to be sorry. Could very well be something I'm doing or something with my account. Let me know what you find! Thanks!

**Comment by CMahaff** [comment]
Total guess: I wonder if it could be password length? Maybe the UI is bugged and cuts off your password - I'm assuming bitwarden auto-generates some very long passwords.

**Comment by esmoyer** [comment]
I could try a shorter one, it's actually the same password I use for .world which works fine but need to change it anyway, so I'll give it a go. It's currently only 21 characters.

**Comment by CMahaff** [comment]
Good news: I was finally able to get a lemmy.ml account and replicate this behavior.

Bad news: Still don't know why I'm running into this just with lemmy.ml and not lemmy.world, lemm.ee, and even voyager.lemmy.ml - which all work fine.

API doesn't seem to be outright disabled either since I can login to lemmy.ml from their Jerboa app and another 3rd party app.

I'll have to keep digging.

**Comment by esmoyer** [comment]
Works great now! Thanks for the quick fix!
