### ISSUE TITLE
How do I run it?

### ISSUE THREAD

**Issue by 8ullyMaguire** [CMahaff/lasim#6]
Is it something like this?

```
git clone https://github.com/CMahaff/lasim.git
cd lasim
make
./lasim
```

**Comment by CMahaff** [comment]
I'll take an action to document this in the README later.

The super short version is you'll need to get the latest versions or rust and cargo, clone the repo, and then do a "cargo r" to run the project in debug mode or "cargo b" to build the executable.

The easier route is just grabbing a pre-built binary from the Releases page, or the GitHub Actions page vs building from source - if you are comfortable with that.

**Comment by 8ullyMaguire** [comment]
I asked the AI and it managed to write a PKGBUILD with your instructions thanks.

> ## PKGBUILD for lasim
> 
> Here is a PKGBUILD file for the lasim project, which can be used to build the package on Manjaro:
> 
> ```bash
> pkgname=lasim
> pkgver=0.1.1
> pkgrel=1
> pkgdesc="Move your Lemmy settings from one account to another"
> arch=('x86_64')
> url="https://github.com/CMahaff/lasim"
> license=('MIT')
> depends=('rust' 'cargo')
> makedepends=('git')
> source=("$pkgname-$pkgver.tar.gz::https://github.com/CMahaff/lasim/archive/refs/tags/v$pkgver.tar.gz")
> sha256sums=('SKIP')
> 
> build() {
>   cd "$srcdir/$pkgname-$pkgver"
>   cargo build --release
> }
> 
> package() {
>   cd "$srcdir/$pkgname-$pkgver"
>   install -Dm755 "target/release/$pkgname" "$pkgdir/usr/bin/$pkgname"
>   install -Dm644 "LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
> }
> ```
> 
> This PKGBUILD file will download the lasim source code from the GitHub repository, build it using Rust and Cargo, and install the resulting binary and license file to the appropriate directories.
> 
> To build and install the package, save the PKGBUILD file to a directory, navigate to that directory in the terminal, and run the following command:
> 
> ```bash
> makepkg -si
> ```
> 
> This will build the package and install it using pacman. After the installation is complete, you can use lasim as described in the project's README.
> 
> Please note that this PKGBUILD is specifically for the lasim version 0.1.1. If a new version is released, you'll need to update the `pkgver` variable and adjust the `source` and `sha256sums` accordingly.
> 
> Citations:
> [1] https://forum.manjaro.org/t/howto-read-a-pkgbuild/116900
> [2] https://wiki.archlinux.org/title/creating_packages
> [3] https://forum.manjaro.org/t/how-to-compile-a-package-from-source/58064
> [4] https://doc.rust-lang.org/cargo/
> [5] https://www.grammy.com/artists/lasim-richards/13997
> [6] https://github.com/CMahaff/lasim
> [7] https://wiki.manjaro.org/index.php/Makepkg
> [8] https://wiki.archlinux.org/title/PKGBUILD
> [9] https://forum.manjaro.org/t/how-to-build-a-package-from-source-on-manjaro/53961
> [10] https://doc.rust-lang.org/book/ch01-03-hello-cargo.html
> [11] https://www.ftc.gov/news-events/news/press-releases/2023/03/ftc-approves-final-order-against-lca-vision-halting-alleged-bait-switch-advertising-lasik-laser-eye
> [12] https://github.com/CMahaff
> [13] https://wiki.manjaro.org/index.php/Create_Manjaro_Packages
> [14] https://itsfoss.com/create-pkgbuild/
> [15] https://forum.manjaro.org/t/howto-fix-a-failing-aur-package-build/104668
> [16] https://doc.rust-lang.org/cargo/getting-started/installation.html
> [17] https://www.ftc.gov/news-events/news/press-releases/2023/01/ftc-order-requires-lasikplus-pay-its-bait-switch-eye-surgery-ads
> [18] https://github.com/CMahaff/lasim/issues
> [19] https://forum.manjaro.org/t/help-with-a-pkgbuild-install/135512
> [20] https://youtube.com/watch?v=crnGzF43aoc
> [21] https://wiki.manjaro.org/index.php/Build_Manjaro_ISOs_with_buildiso
> [22] https://crates.io
> [23] https://www.allaboutjazz.com/musicians/lasim-richards
> [24] https://github.com/topics/account?o=desc&s=updated
> [25] https://forum.manjaro.org/t/pacman-and-custom-pkgbuild/115672
> [26] https://www.arcolinuxiso.com/creating-a-pkgbuild-from-scratch-and-putting-it-on-aur/
> [27] https://operavps.com/docs/manjaro-package-manager/
> [28] https://youtube.com/watch?v=DHMTfWCnYcs
> [29] https://jaxsta.com/profile/14203a75-d4f6-48d7-a49f-afa70cf86461/catalogue
> [30] https://github.com/Lasim
> [31] https://forum.manjaro.org/t/need-help-creating-a-pkgbuild/118996
> [32] https://www.arcolinuxiso.com/creating-a-pkgbuild-from-scratch-and-putting-it-online-on-aur-from-a-till-aur/
> [33] https://rust.fandom.com/wiki/Cargo_Ship
> [34] https://www.mereommig.dk/comment/11426
> [35] https://lemmy.eus/post/193097?scrollToComments=true
> [36] https://www.mankier.com/5/PKGBUILD
> [37] https://github.com/rust-lang/cargo
> [38] https://lemmy.trevor.coffee/post/6468
> [39] https://wiki.manjaro.org/index.php/PKGBUILD
> [40] http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/cargo/print.html
> [41] https://lemmy.trevor.coffee/comment/33669
