### ISSUE TITLE
Wrong permissions on executable for Ubuntu / Linux and maybe OS X

### ISSUE THREAD

**Issue by CMahaff** [CMahaff/lasim#7]
**Describe the Bug**
LASIM binaries are downloaded without 755 permissions, so when you try to run them Ubuntu doesn't understand what to do with it until it is changed. The same thing might be happening in OS X as well.

**Information**
LASIM Version: 0.1.1
LASIM Profile Version: 1
Lemmy Source Instance URL: N/A
Lemmy Source Instance Version: N/A
Lemmy Target Instance URL: N/A
Lemmy Target Instance Version: N/A

**Output of LASIM**
N/A

**Comment by chrismarquardt** [comment]
Same for macOS - after ```chmod +x lasim``` it worked

**Comment by CMahaff** [comment]
> Same for macOS - after ```chmod +x lasim``` it worked 

Thanks for confirming my suspicions!

If you get a minute, could you try the artifact here? It should be setting the permissions on the LASIM file at build time: https://github.com/CMahaff/lasim/actions/runs/5515129357
